In [1]:
print("hello")

hello


In [2]:
def hello():
    print("hello how are you")

In [4]:
hello()

hello how are you


In [1]:
import numpy as np

In [ ]:
arr = np.array([1, 2, 3, 4])
arr

array([1, 2, 3, 4])

In [3]:
a = [1, 2, 3, 4]
a

[1, 2, 3, 4]

In [4]:
np.array(a)

array([1, 2, 3, 4])

In [3]:
import numpy as np
l = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [4]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
arr = np.arange(1, 11, 2)
arr

array([1, 3, 5, 7, 9])

In [9]:
arr = np.zeros((6, 6))
arr

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [12]:
arr = np.linspace(1, 5, 3)
arr

array([1., 3., 5.])

In [2]:
import numpy as np
np.random.rand(10)

array([0.3590363 , 0.1138085 , 0.64006901, 0.84509084, 0.73444912,
       0.22338667, 0.65105145, 0.74080593, 0.64387525, 0.13119415])

In [3]:
np.random.randn(10)

array([-0.4737346 ,  0.04742205,  0.24415597,  2.80585657, -1.21571982,
        0.01012367,  0.2118635 ,  0.09811198, -0.06919695, -1.07391054])

In [4]:
np.random.randint(10, 20, 10)

array([12, 19, 15, 13, 12, 11, 16, 18, 14, 16], dtype=int32)

In [3]:
import numpy as np
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
arr.shape

(3, 3)

In [5]:
arr.size

9

In [6]:
arr.max

<function ndarray.max>

In [7]:
arr.min()

np.int64(1)

In [8]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
arr.min()

np.int64(1)

In [12]:
arr.max()

np.int64(9)

In [13]:
arr.sum()

np.int64(45)

In [17]:
np.sum(arr, axis=0)

array([12, 15, 18])

In [19]:
arr.argmax()

np.int64(8)

In [20]:
arr.mean()

np.float64(5.0)

In [21]:
arr.std()

np.float64(2.581988897471611)

In [22]:
arr.argmin()

np.int64(0)

In [27]:
arr = np.arange(1, 101)
arr

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [29]:
arr[3::2]

array([  4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,  28,
        30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,  54,
        56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,  80,
        82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [33]:
import numpy as np
arr = np.arange(11, 21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [35]:
arr_slice = arr[3::2]
arr_slice

array([14, 16, 18, 20])

In [36]:
arr[4]

np.int64(15)

In [40]:
arr = np.arange(1,31).reshape(6, 5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [41]:
arr[0]

array([1, 2, 3, 4, 5])

In [42]:
arr[0,0]

np.int64(1)

In [44]:
arr[0,4]

np.int64(5)

In [45]:
arr[5, 3]

np.int64(29)

In [47]:
slice = arr[0:2, 1:3]
slice

array([[2, 3],
       [7, 8]])

In [2]:
import numpy as np
arr = np.arange(11, 21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [3]:
bool_index = arr %2 == 0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [4]:
arr = arr[bool_index]
arr

array([12, 14, 16, 18, 20])