In [3]:
import numpy as np

In [5]:
a1 = np.array([1, 2, 3, 4, 5])
a2 = np.array([6, 7, 8, 9, 10])

In [6]:
 a1 + a2

array([ 7,  9, 11, 13, 15])

In [7]:
a1 - a2

array([-5, -5, -5, -5, -5])

In [8]:
a1 * a2

array([ 6, 14, 24, 36, 50])

In [9]:
a1 / a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [10]:
a1 // a2

array([0, 0, 0, 0, 0])

In [11]:
l = [10, 20, 30, 40]
arr = np.array(l)

In [12]:
for i in l:
    print(i * 10)

100
200
300
400


In [13]:
arr + 10

array([20, 30, 40, 50])

In [15]:
a = np.arange(1, 21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [19]:
slice = a[:5]
slice * 10

array([10, 20, 30, 40, 50])

In [23]:
a
b = a.copy()

In [24]:
b[0] = 99

In [25]:
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [26]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

In [27]:
A

array([[1, 2],
       [3, 4]])

In [28]:
B

array([[5, 6],
       [7, 8]])

In [29]:
A * B

array([[ 5, 12],
       [21, 32]])